<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>passwordField</name>
   <tag></tag>
   <elementGuidId>b29db8ce-392b-4889-9ec9-8f84dc8d8dac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[type='password']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>input[type='password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
