<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ceklist_btn</name>
   <tag></tag>
   <elementGuidId>dc9e98ef-a6c0-497b-a1f0-aec6c7db0e77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[id='ok-check']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>input[id='ok-check']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
