<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>daftarField</name>
   <tag></tag>
   <elementGuidId>d0d4a7af-5ac9-4586-90f9-a57d7a220ed4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name='${name}']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
