<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>daftarConfirm_btn</name>
   <tag></tag>
   <elementGuidId>c548759a-e12b-4f78-9212-7d7f0f96d5b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[type=submit]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
