<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>account_btn</name>
   <tag></tag>
   <elementGuidId>296be76a-10a9-4e2c-b728-08e6e2797635</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.Anchor-NexLink-Function</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
