<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>daftar_btn</name>
   <tag></tag>
   <elementGuidId>0b2d0804-2347-4e5b-87af-000b8909884f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.sc-dkPtyc.hjXmuM</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
